// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using netcore_reactapi.Models;

namespace netcore_reactapi.Migrations
{
    [DbContext(typeof(EmpDBContext))]
    partial class EmpDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("netcore_reactapi.Models.Employee", b =>
                {
                    b.Property<int>("empid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("empname")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("mobile")
                        .HasColumnType("varchar(100)");

                    b.HasKey("empid");

                    b.ToTable("Employeedb");
                });
#pragma warning restore 612, 618
        }
    }
}
